### PR TITLE
Check isArrayBuffer natively

### PR DESCRIPTION
**Pull request by cktang88**
Removes need for external dependencies. All tests pass.

### CODE REVIEW

**Comment by LinusU** [comment]
I haven't tested this yet but I have a feeling that this will fail for ArrayBuffers that are passed up from a child iframe, or created in another context 🤔

**Comment by cktang88** [comment]
Ah, good catch. I think I've fixed it now, by replacing instanceOf with the object constructor's toString() method, which is more robust.

**Comment by cktang88** [comment]
@LinusU Have you considered my changes?

**Comment by LinusU** [comment]
I've been a bit reluctant towards this since it seems like we are just copying code into this project, which we now have to maintain. But I just realized that `is-array-buffer-x` is 3.8 megs of dependencies 😱 

I fixed this slightly different in c26ed51768c25445d058e77444c303140fcb2c20 (released as 0.1.2 and 1.0.0). That implmentation mirrors 1) what I've mostly seen in the wild, and 2) [@sindresorhus/is](https://github.com/sindresorhus/is/blob/fd32b11b6d1ce6adab866464992ecb5bd126c603/source/index.ts#L36-L51).

Thank you so much for pushing this forward 👍 ❤️

**Pull request closed without merging**
