### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by Parcley**
useful for tools, which automatically check license compliance of open source projects

### CODE REVIEW

**Comment by LinusU** [comment]
The license is specified as `MIT` in the package.json, do you know of any tool that won't pick it up from there?

**Comment by kylef** [comment]
I believe that isn't legally sufficient. The MIT license itself says that I need to have the copyright notice in any copies. There would be no copyright notice without the full license and thus render the license invalid:

> Copyright (c) Linus Unnebäck <linus@folkdatorn.se>
> 
> Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, *subject to the following conditions*:
>
> **The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.**

**Comment by Parcley** [comment]
@LinusU: 
I was using https://github.com/davglass/license-checker @ 11.0.0 for checking licensing of all my depdencies. Not sure if recent versions of license checker work differently. 

@kylef:
you might have a point. But when buffer-from is distributed (either cia git pull or npm install), in both cases the LICENSE file will be distributed along. Could that be sufficient?

**Comment by kylef** [comment]
@Parcley Sorry, my comment wasn't at the PR/your changes but regarding @LinusU comment. I've edited my comment to make it clearer.

**Comment by LinusU** [comment]
I opened this a while back and which was downvoted, I guess that the consensus is that a license file is needed...

https://softwareengineering.stackexchange.com/questions/358554/do-i-need-a-dedicated-license-file-when-license-is-specified-elsewhere

I added one with the copyright years specified in 286425a

Thanks for the help everyone!

**Pull request closed without merging**
